# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from symphony.v1 import protocol_pb2 as symphony_dot_v1_dot_protocol__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in symphony/v1/protocol_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ConductorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
            "/symphony.v1.ConductorService/Connect",
            request_serializer=symphony_dot_v1_dot_protocol__pb2.NodeToConductor.SerializeToString,
            response_deserializer=symphony_dot_v1_dot_protocol__pb2.ConductorToNode.FromString,
            _registered_method=True,
        )


class ConductorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ConductorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Connect": grpc.stream_stream_rpc_method_handler(
            servicer.Connect,
            request_deserializer=symphony_dot_v1_dot_protocol__pb2.NodeToConductor.FromString,
            response_serializer=symphony_dot_v1_dot_protocol__pb2.ConductorToNode.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "symphony.v1.ConductorService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "symphony.v1.ConductorService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class ConductorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/symphony.v1.ConductorService/Connect",
            symphony_dot_v1_dot_protocol__pb2.NodeToConductor.SerializeToString,
            symphony_dot_v1_dot_protocol__pb2.ConductorToNode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
